### ISSUE TITLE
A bytes-like object is required, not 'str'

### ISSUE THREAD

**Issue by morettimatheus** [scardine/SabreAPI#2]
Hello,
I'm trying to use your code to make requests to Sabre API. First of all I'd like to thank you for uploading this to GitHub :smile: 

Using Python 3.5, I get the following error when assigning client_id and _secret

`client_id = "V1:XXXXXXXXX:DEVCENTER:EXT"
client_secret = "XXXXX"`

sabre = Sabre(client_id, client_secret)`

`Traceback (most recent call last):
  File "C:/Users/Consultor/Desktop/PYTHON/GetDataQPX/Sabre/request.py", line 6, in <module>
    sabre = Sabre(client_id, client_secret)
  File "C:\Users\Consultor\Desktop\PYTHON\GetDataQPX\Sabre\sabreAPI.py", line 49, in __init__
    self.credentials = self.encode_credentials()
  File "C:\Users\Consultor\Desktop\PYTHON\GetDataQPX\Sabre\sabreAPI.py", line 106, in encode_credentials
    client_id=base64.b64encode(self.client_id),
  File "C:\Users\Consultor\AppData\Local\Programs\Python\Python35-32\lib\base64.py", line 62, in b64encode
    encoded = binascii.b2a_base64(s)[:-1]
TypeError: a bytes-like object is required, not 'str'`

Tried to encode it, but had no success. Could you please help me?

Thankful

Matheus

**Comment by morettimatheus** [comment]
This is an issue related to Python 3.x.

**Comment by scardine** [comment]
I guess I should fix this in order to make the code work on Python 3.x, so I will reopen. Thanks for reporting.

**Comment by Gunjan7991** [comment]
Hello,
I am very grateful for your post. It is very hard to find such valuable material based on SabreAPI elsewhere.
Currently, I'm trying to use your code to make requests to Sabre API. Using Python 3.8, I get the following error when assigning client_id and _secret

sabre = Sabre(key1, key2)
where key1 = client_id
           key2 = client_secret
I even tried encoding the keys but it didn't work for me. Currently, I  am getting following errors:

Traceback (most recent call last):
  File "C:/Users/Home/Desktop/eel/engine/test.py", line 11, in <module>
    sabre = Sabre(key1, key2)
  File "C:\Users\Home\Desktop\eel\engine\SabreAPI.py", line 41, in __init__
    self.credentials = self.encode_credentials()  
  File "C:\Users\Home\Desktop\eel\engine\SabreAPI.py", line 96, in encode_credentials
    return base64.b64encode("{client_id}:{client_secret}".format(
  File "C:\Users\Home\AppData\Local\Programs\Python\Python38\lib\base64.py", line 58, in b64encode
    encoded = binascii.b2a_base64(s, newline=False)
TypeError: a bytes-like object is required, not 'str

Thank you in advance.
